// <?php 
// $books = array(
//     array("bookname" => "HTML and CSS",
//         "author" => "Jon Duckett",
//         "price" => "17.19$",
//         "description" => "Every day, more and more people want to learn some ...",
//         "image" => "HTMLandCSS_Duckett.jpg"),
//     array("bookname" => "HTML5",
//         "author" => "Matthew MacDonald",
//         "price" => "27.65$",
//         "description" => "HTML is more than a markup language ...",
//         "image" => "HTML5TheMissing_MacDonald.jpg"),
//     array("bookname" => "Head First HTML5 Programming",
//         "author" => "Eric Freeman, Elisabeth Rosbon",
//         "price" => "35.35$",
//         "description" => "HTML has been on a wild ride. Sure, html...",
//         "image" => "HeadFirstHTML5.jpg"),
//     array("bookname" => "Head First JavaScript Porgramming",
//         "author" => "Eric Freeman, Elisabeth Rosbon",
//         "price" => "39.35$",
//         "description" => "This brain-friendly guide teaches you everything...",
//         "image" => "HeadFirstJavaScript.jpg"),
//     array("bookname" => "jQuery in Action",
//         "author" => "Bear Bibeault, Yehuda Katz",
//         "price" => "37.43$",
//         "description" => "A really good web development frameworkd in the world!",
//         "image" => "JQueryInAction.jpg"));
// ?>        